version: '3.7'
services:
  incredy-front:
    container_name: incredy-front
    build:
      context: . #PATH TO Dockerfile
      args:
        APP_CONFIG_FILE_PATH: 'docker_resources/appConfig.js'
    image: incredy-front:latest
    ports:
      - '80:80'
    network_mode: 'host'
